### ISSUE TITLE
Publish skrooge to pypi

### ISSUE THREAD

**Issue by mwarkentin** [getsentry/skrooge#8]
Make it as simple as `pip install skrooge`

https://develop.sentry.dev/sdk/craft-quick-start/
```[tasklist]
### Tasks
- [x] Tag beginning of repository
- [x] Produce artifact
- [x] Set up craft
- [x] Create scripts/bump-version.sh
- [x] Create release workflow
- [x] Set up permissions
- [x] Create first release!
```

**Comment by mwarkentin** [comment]
Blocked by https://github.com/getsentry/publish/issues/3316
